<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text12_text12</name>
   <tag></tag>
   <elementGuidId>8816316e-04fa-41d8-8f99-141702d44469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text12']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>852096ec-ea82-43fa-9478-b5509250570b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62d68364-2de2-46d3-8e4a-b3f63ab22ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text12</value>
      <webElementGuid>1197a7e5-2daa-4bc5-b5ef-6b2230ad8069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text12&quot;)</value>
      <webElementGuid>69c1360f-e20d-46f2-92a8-a04c8e2e6a11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text12']</value>
      <webElementGuid>ce509fb5-a1e2-430e-9c46-0f7a13760a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[12]</value>
      <webElementGuid>24567c61-0b9d-4b98-8927-5c1e2c54bcbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text12']</value>
      <webElementGuid>3de43a57-2d47-4342-8625-3aec7abe9c44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
