<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text16_text16</name>
   <tag></tag>
   <elementGuidId>d80e2844-dd1c-4961-a2ee-ccb53cb06d14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e46a5e19-c36e-466c-9fc6-c773bc7b5617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>274ab448-168d-48c0-a501-e11f5ebbdfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text16</value>
      <webElementGuid>1e35b477-258e-4d44-823b-370cca8ac0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text16&quot;)</value>
      <webElementGuid>80840723-9ef8-4d79-9bae-87fa6b5c2258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text16']</value>
      <webElementGuid>0627d4ac-727f-49e3-8796-1747dbf90ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[16]</value>
      <webElementGuid>e98e0e64-d325-4449-8576-bf29f7c7edfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text16']</value>
      <webElementGuid>5e8ed1fb-19ed-4447-8db9-48dae7a42c2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
