<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text22_text22</name>
   <tag></tag>
   <elementGuidId>6afeb227-0bb0-4deb-8579-b2f185a394a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text22']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text22</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b166eff7-b623-45d9-98a0-987b03cc55fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e82a726c-1d21-48f7-a3e9-d4b4a70a62cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text22</value>
      <webElementGuid>f93f7e08-88f7-409a-977f-f06dca30e56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text22&quot;)</value>
      <webElementGuid>c82b481d-f82a-487d-bc94-cdab6ceba479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text22']</value>
      <webElementGuid>48a77528-afac-43b5-90e5-74fdd42fdbe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[22]</value>
      <webElementGuid>e2ae5281-8dcf-40d1-aec3-d6a621feb18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text22']</value>
      <webElementGuid>b22c7baf-906e-4ae9-8832-a7470e09d24a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
