<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text30_text30</name>
   <tag></tag>
   <elementGuidId>bebffda1-d406-4047-969f-897e2f9e3720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text30']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text30</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30cdeead-60aa-4d89-a385-d64de99f0da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a93987c6-34f1-4ed5-a96c-a2fe02c68539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text30</value>
      <webElementGuid>96538508-405e-466e-af84-86dd295a7080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text30&quot;)</value>
      <webElementGuid>d30dcedf-7c7a-43c1-ac63-b07c8ef7da99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text30']</value>
      <webElementGuid>7eb33a86-baff-40e7-9d57-2e6e92ac8679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[30]</value>
      <webElementGuid>7f3c5fd6-2b9e-4660-9e8f-0158bd6fc660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text30']</value>
      <webElementGuid>29d3bf9c-f8c1-4db4-8817-bc1d9c1f746e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
