<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text37_text37</name>
   <tag></tag>
   <elementGuidId>8ab5863f-f1ff-4651-89ce-fa9fdfd9647c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text37']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text37</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b7d6ccc-2099-4e0e-ad26-67ca110b0125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>720c3d76-d774-44ba-a87b-2dd8ca230f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text37</value>
      <webElementGuid>1771e6f8-fad7-472e-b048-64d7a98a1970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text37&quot;)</value>
      <webElementGuid>3a4fc55c-e935-482e-be62-44b5679cd019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text37']</value>
      <webElementGuid>80e0ac72-3fa4-4b8c-98c9-39dde6992fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[37]</value>
      <webElementGuid>2c0a5cd2-82ac-4317-b2a7-97be4f16f1b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text37']</value>
      <webElementGuid>870527c9-27bb-4324-9639-4f05c04012fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
