<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text35_text35</name>
   <tag></tag>
   <elementGuidId>73364307-d3d2-407b-b41a-41456f180a29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text35']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text35</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb4ddf01-43ad-42cf-a5ec-3d4ce7ac78c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df697dcd-d3bc-4bcb-8c2a-1a820f3f1a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text35</value>
      <webElementGuid>f1d0234b-305f-4226-a3b5-3a8b5f249d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text35&quot;)</value>
      <webElementGuid>4f901635-f6aa-4db7-a2ec-ac0b0ca7ccbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text35']</value>
      <webElementGuid>f0664d46-1248-44db-9dcb-e33b3fa3b584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[35]</value>
      <webElementGuid>aaf7c3a2-dbf2-4ef1-a968-3ea11d4b0f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text35']</value>
      <webElementGuid>348fd788-1c95-47cb-9213-84b73f304a01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
