<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Checkbox1_checkbox2</name>
   <tag></tag>
   <elementGuidId>b25331e5-0033-4f60-b9a0-72355b458b63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>880e23a1-606d-4240-99e0-84fe05f7915e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>176392de-34ed-40c4-8d2b-d4cb84010949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox2</value>
      <webElementGuid>705adece-69ff-4e27-a642-2243cec62c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checkbox2</value>
      <webElementGuid>48dcbb1c-971e-4a06-871f-eb5f9b7dfa56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox2&quot;)</value>
      <webElementGuid>2337d52c-ff8c-4061-8c44-8b4081745894</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox2']</value>
      <webElementGuid>652ad860-28ec-4093-8590-f245c6cdc41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[12]</value>
      <webElementGuid>ac084b83-4923-4a5e-ab7f-fda1eaf964ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox2']</value>
      <webElementGuid>9a30912d-7d75-4979-ac7a-c1f62c7b1364</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
