<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Checkbox9_checkbox10</name>
   <tag></tag>
   <elementGuidId>bbe9556b-a52b-4262-ab07-ee7da9272422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce6cddcc-7c92-429a-a43f-4f6bd957939b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c1f2bb9d-b840-4375-a593-1fe1a4a5acb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox10</value>
      <webElementGuid>e620c3ca-17b6-4e71-b959-9954cf80481a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checkbox10</value>
      <webElementGuid>fa209b94-0a8b-421e-b19c-c4eae7f77299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox10&quot;)</value>
      <webElementGuid>24bf8e17-83c2-4469-87d3-bf5a170313f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox10']</value>
      <webElementGuid>0ea67bdd-1334-4736-a2c6-11464f4a71ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[20]</value>
      <webElementGuid>a79a602a-8eae-4e70-adc5-ad7c1f4d4f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox10']</value>
      <webElementGuid>2a3a600e-012b-4214-9fc5-60baca3baa12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
