<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Checkbox8_checkbox9</name>
   <tag></tag>
   <elementGuidId>84c17492-a00b-46e3-a2c6-f02f500b2d49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ed1268b-898e-41d1-9575-034e3fc23be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>35a3889a-aac5-4c6d-8eef-bb338f180742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox9</value>
      <webElementGuid>1e4ba9d7-b600-4a35-a69a-65f0ed1e46e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checkbox9</value>
      <webElementGuid>41c663bc-3314-423d-b696-3b50b5533792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox9&quot;)</value>
      <webElementGuid>ecb273e2-7c87-4fa5-b9b9-6f23179348f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox9']</value>
      <webElementGuid>8c5ef9d2-09ac-4295-a6ee-bd2f96d48d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[19]</value>
      <webElementGuid>2b42f015-2daa-479d-a5a9-7febeb736906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox9']</value>
      <webElementGuid>0f2ae84e-f952-419b-ab45-0efcdd18c77a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
