<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio9_radio10</name>
   <tag></tag>
   <elementGuidId>2c727651-6de1-485f-8258-cf08451deae1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a0bc099-4a12-4b9a-b55c-e5e62a59f0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c9d59c9c-2fb4-4939-9c7d-810a8144605f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio10</value>
      <webElementGuid>0be3eb95-40e2-4c9d-a742-3a9e0de547ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio10</value>
      <webElementGuid>4a5afc75-e9f9-4591-a65f-022fded55675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio10&quot;)</value>
      <webElementGuid>f7c7e6d9-ef67-461a-8be0-40e2ebfa884b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio10']</value>
      <webElementGuid>393ad4ad-8bbc-4613-936d-3a8c7a4d88a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[30]</value>
      <webElementGuid>16e2cb6c-c7e5-4d5d-920a-45a806e3a6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio10']</value>
      <webElementGuid>f2c1fa5a-38b2-4641-8c3d-5afb5c777ba8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
