<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio7_radio8</name>
   <tag></tag>
   <elementGuidId>ffde8e2f-a35d-47f8-b26b-c4800e538413</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>033c5515-8fae-45c6-a212-3d5c9b4584d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2489ee63-55c8-4360-aea3-d7d3f5b42d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio8</value>
      <webElementGuid>c603d52e-d544-4d0a-b8a1-8fa05f398842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio8</value>
      <webElementGuid>e066ceb6-f861-4905-ba5e-921a54c4ed8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio8&quot;)</value>
      <webElementGuid>98691ab3-f18f-4f2a-a3d9-a75546fad948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio8']</value>
      <webElementGuid>c8b4b668-74bd-4332-b381-e5a9b351630b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[28]</value>
      <webElementGuid>aa0fbc2e-2396-4a49-9329-1896310eaa53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio8']</value>
      <webElementGuid>baeebe3f-495d-4704-8776-a40c24095189</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
